"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information:
https://docs.djangoproject.com/en/5.2/topics/settings/
"""

from pathlib import Path

# --------------------------
# BASE DIRECTORY
# --------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# --------------------------
# SECURITY
# --------------------------
SECRET_KEY = 'django-insecure-2&(znt%!19ah5%0=3q4@6i4x-y0hv)cz*ngd%zc9)pu2lzy@i+'
DEBUG = True
ALLOWED_HOSTS = []

# --------------------------
# INSTALLED APPS
# --------------------------
INSTALLED_APPS = [
    "corsheaders",               # CORS
    "rest_framework",            # DRF
    "users",                     # User app
    "loans",                     # Loan app
    "savings",                   # Savings app
    "payments",                  # Payment app

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# --------------------------
# MIDDLEWARE
# --------------------------
MIDDLEWARE = [
  
   "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",]

# --------------------------
# CORS CONFIGURATION
# --------------------------
# settings.py
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',  # React frontend
]

# --------------------------
# MEDIA & STATIC FILES
# --------------------------
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media/"

STATIC_URL = 'static/'
ROOT_URLCONF = "backend.urls"
# --------------------------
# URLS & AUTH
# --------------------------
ROOT_URLCONF = 'backend.urls'
WSGI_APPLICATION = 'backend.wsgi.application'

AUTH_USER_MODEL = 'users.User'

# --------------------------
# TEMPLATES
# --------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# --------------------------
# DATABASE CONFIGURATION (MySQL)
# --------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'arifpay_db',
        'USER': 'root',
        'PASSWORD': '',           # <-- Add your MySQL password
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
]


# --------------------------
# PASSWORD VALIDATION
# --------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --------------------------
# INTERNATIONALIZATION
# --------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --------------------------
# REST FRAMEWORK SETTINGS
# --------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}


# --------------------------
# DEFAULT PRIMARY KEY FIELD
# --------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = "users.User"

# Simple JWT settings (optional customization)
from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}