# Generated by Django 5.2.7 on 2025-10-28 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loandocument',
            name='loan',
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('id_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=50)),
                ('income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employment', models.CharField(max_length=100)),
                ('obligations', models.CharField(blank=True, max_length=255)),
                ('bank_account', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.CharField(max_length=255)),
                ('duration_months', models.IntegerField()),
                ('repayment_plan', models.CharField(max_length=255)),
                ('collateral', models.CharField(blank=True, max_length=255)),
                ('id_proof', models.FileField(upload_to='loan_docs/')),
                ('salary_slip', models.FileField(upload_to='loan_docs/')),
                ('bank_statement', models.FileField(upload_to='loan_docs/')),
                ('collateral_doc', models.FileField(blank=True, upload_to='loan_docs/')),
                ('consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='LoanDocument',
        ),
    ]
