# Generated by Django 5.2.7 on 2025-10-29 08:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_remove_loandocument_loan_loanapplication_delete_loan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='bank_statement',
            field=models.FileField(upload_to='loan_docs/bank_statements/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='collateral',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='collateral_doc',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/collateral_docs/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='id_proof',
            field=models.FileField(upload_to='loan_docs/id_proofs/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='obligations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='salary_slip',
            field=models.FileField(upload_to='loan_docs/salary_slips/'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['user'], name='loans_loana_user_id_7a75dc_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['status'], name='loans_loana_status_ff4c26_idx'),
        ),
    ]
