# Generated by Django 5.2.7 on 2025-10-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loanapplication_bank_statement_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loanapplication',
            name='loans_loana_user_id_7a75dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='loanapplication',
            name='loans_loana_status_ff4c26_idx',
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='collateral_doc',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='salary_slip',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/'),
        ),
    ]
