# Generated by Django 5.2.7 on 2025-10-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_remove_loanapplication_loans_loana_user_id_7a75dc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/bank_statements/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='collateral_doc',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/collateral/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/id_proofs/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='salary_slip',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/salary_slips/'),
        ),
    ]
