# Generated by Django 5.2.7 on 2025-10-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_alter_loanapplication_bank_statement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='collateral',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='collateral_doc',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='obligations',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='salary_slip',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/'),
        ),
    ]
