# Generated by Django 5.2.7 on 2025-10-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_loanapplication_bank_statement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='address',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='collateral',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='duration_months',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='employment',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='income',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='obligations',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='repayment_plan',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='business_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='business_license_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='business_sector',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='father_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='grandfather_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='kebele_id',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='legal_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='mobile1',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='mobile2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='nisir_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='purpose_of_loan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='specific_location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='sub_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='title',
            field=models.CharField(default='Mr./Ms.', max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='woreda',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='zone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/bank_statements/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='collateral_doc',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/collateral/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/id_proofs/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='salary_slip',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/salary_slips/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
