# Generated by Django 5.2.7 on 2025-10-30 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_remove_loanapplication_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='stage',
            field=models.CharField(choices=[('pending', 'Pending'), ('first_screening', 'First Screening'), ('approved', 'Approved'), ('active', 'Active Loan'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
