# Generated by Django 5.2.7 on 2025-10-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_loanapplication_due_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplication',
            old_name='reminder_sent',
            new_name='screening_completed',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='proposed_monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='repayment_period_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='stage',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
